# Generated by Django 3.0.8 on 2020-07-10 10:59

import awesome_avatar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200710_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=awesome_avatar.fields.AvatarField(upload_to='profile_pics/'),
        ),
    ]
