# Generated by Django 3.0.8 on 2020-07-10 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200710_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
