# Generated by Django 3.0.8 on 2020-07-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
