# Generated by Django 3.0.8 on 2020-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200702_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
