# Generated by Django 3.0.7 on 2020-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200629_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='notes_pics'),
        ),
    ]
