# Generated by Django 3.0.7 on 2020-06-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_categ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='categ',
        ),
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(default='CS', max_length=10),
        ),
    ]
