# Generated by Django 3.0.7 on 2020-06-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200625_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(default='CS', max_length=25),
        ),
    ]
