# Generated by Django 3.0.8 on 2020-07-04 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='notes_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
