# Generated by Django 3.0.7 on 2020-06-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200627_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='cars'),
        ),
    ]
