# Generated by Django 3.0.8 on 2020-07-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200705_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
