# Generated by Django 3.0.7 on 2020-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200630_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes_pics/'),
        ),
    ]
