# Generated by Django 3.0.8 on 2020-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
