# Generated by Django 3.0.7 on 2020-06-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20200630_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='slug',
        ),
    ]
