# Generated by Django 3.0.7 on 2020-06-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank='True', null=True, upload_to='notes_pics/'),
        ),
    ]
