# Generated by Django 3.0.8 on 2020-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
