# Generated by Django 3.0.8 on 2020-07-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20200711_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='likes',
        ),
    ]
